options:
  # Option 1: Use regional user-owned bucket (recommended)
  logging: CLOUD_LOGGING_ONLY
  # Option 2: Alternatively specify a logs bucket
  # logsBucket: 'gs://your-log-bucket-name'

steps:
  # Build with Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
  
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/springboot-cloudrun', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/springboot-cloudrun']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'springboot-cloudrun', 
           '--image', 'gcr.io/$PROJECT_ID/springboot-cloudrun',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/springboot-cloudrun'
